version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.example.com # Replace with your own hostname
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com' # Replace with your own URL
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "your_email@gmail.com" # Replace with your own email
        gitlab_rails['smtp_password'] = "your_email_password" # Replace with your own email password
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
    ports:
      - "8003:80"
      - "8443:443"
      - "8022:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    environment:
      GITLAB_URL: http://gitlab.example.com # Replace with your own URL
      REGISTRATION_TOKEN: your_registration_token # Replace with your own registration token
      RUNNER_NAME: gitlab-runner
      RUNNER_EXECUTOR: docker
      DOCKER_IMAGE: docker:latest
      DOCKER_PRIVILEGED: true
      DOCKER_TLS_CERTDIR: ""
      DOCKER_RUN_PRIVILEGED: true
      DOCKER_VOLUMES: "/cache"
      DOCKER_NETWORK_MODE: "host"
      DOCKER_EXTRA_HOSTS: "git.cashcn.xyz:127.0.0.1"
      DOCKER_PORT_BINDINGS: "80:80,443:443"
      DOCKER_ALLOWED_IMAGES: "your/docker-image:tag"
      DOCKER_MEMORY_LIMIT: "2g"
      DOCKER_MEMORY_SWAP_LIMIT: "4g"
      DOCKER_CPUS: "1"
      DOCKER_CPU_SET: "0"
      DOCKER_MEMORY_SWAPPINESS: "0"
      DOCKER_DISABLE_ENTRYPOINT_OVERWRITE: "true"
      DOCKER_WAIT_FOR_SERVICES_TIMEOUT: "60"
